version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ".env"
    depends_on:
      - "db"

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: qwerty
